# This is a basic workflow

name: actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Pre-commit"
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: pre-commit
        uses: pre-commit/action@v3.0.0

  dockerfilerun:
    name: RunDockerfile
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: 'docker'
        image: 'Dockerfile'


  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    needs: dockerfilerun
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_UPDATE: "True"
          PULL_REQUEST_BRANCH: "deploy"
          PULL_REQUEST_TITLE: "This is an AUTO PR; generated because you're lazy"
          PULL_REQUEST_BODY: "The Justice league has approved this PR"
